spring:
  application:
    name: usuario-servicio
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service:8888
  datasource:
    url: jdbc:mysql://mysql:3306/usuariosbd
    username: root
    password: root

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
