server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/