name: Run Test
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test-microservices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: [
          'microservicio-asignaturas',
          'microservicio-estudiantes',
          'usuario-servicio'
        ]
   
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.microservice }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.microservice }}-
 
      - name: Run Tests
        run: mvn test
        working-directory: ./${{ matrix.microservice }}